name: Monitor Grantów
on:
  schedule:
    # Uruchamia 3 razy w tygodniu: poniedziałek, środa, piątek o 9:00 UTC (10:00 czasu polskiego)
    - cron: '0 9 * * 1,3,5'
  # Pozwala na ręczne uruchomienie z zakładki Actions
  workflow_dispatch:

jobs:
  monitor-grants:
    runs-on: ubuntu-latest
    steps:
    - name: Pobierz kod
      uses: actions/checkout@v4
      
    - name: Zainstaluj Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Zainstaluj biblioteki
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Uruchom agent monitorujący
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: python src/scraper.py